ABChaeeun/Algorithm-everyday

hyesu/문자열/1912.py

[연속합(https://www.acmicpc.net/problem/1912)](https://www.acmicpc.net/problem/1912)
처음에 
``` python
d[idx] = max(d[idx-1], d[idx-1] + data[idx])
```
이렇게 잘못 생각했었다,, 저러면 걍 더해지기만함..

[BOJ] 연속합(1912/silver2)

---

chaeeun/SWEA/D1/서랍의비밀번호.py
chaeeun/sample.py

[2043]
https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=1&contestProbId=AV5QJ_8KAx8DFAUq&categoryId=AV5QJ_8KAx8DFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=1&pageSize=10&pageIndex=2
break에 대해 좀 더 공부가 필요할것 같당.

[SWEA] 22-10-07 (서랍의 비밀번호)

---

chaeeun/SWEA/D1/몫과나머지출력하기.py

2029. 몫과 나머지 출력하기
파이썬에서는
a, b = 0
이렇게 안된다!
a = 0; b = 0
이런식으로 해야 가능!!

[SWEA/D1] 22-10-07 (몫과 나머지 출력하기)

---

minjung/백준/14502.py
minjung/백준/16236.py

14502 [연구소](https://www.acmicpc.net/problem/14502)
모든 경우의수를 체크, 벽을 먼저 세우고 -> 바이러스 퍼지는 지점 하나하나 카운팅 !

[14502] 연구소 (BOJ/Gold4)

---

chaeeun/SWEA/D1/대각선출력하기.py

[SWEA/D1] 22-10-09 (대각선 출력하기)

---

hyesu/DP/9461.py

https://www.acmicpc.net/problem/9461
파도반 수열 점화식 d[n] = d[n-1] + d[n-5]
n이 5보다 작은 경우에 대비해서 분기처리를 해쓴데 .. 이게맞나

[BOJ] 22-10-09 (파도반수열/실버3)

---

minjung/백준/14888.py

[14888] [연산자 끼워넣기](https://www.acmicpc.net/problem/14888)
dfs 1부터 시작하는 이유 :: 한칸씩 깊게 들어가면서 depth 인덱스의 number를 불러줘야 하기 때문에 0부터 시작하면 오류난다..

[14888] 22-10-10(월) 연산자 끼워넣기 (BOJ/Silver1)

---

chaeeun/SWEA/D1/더블더블.py

[SWEA/D1] 22-10-10 (더블더블)

---

hyesu/DP/1463.py

https://www.acmicpc.net/problem/1463
나는 배열 추가해가면서 했는데
아래와 같은 코드로 하면 좀더 빠르게 풀 수 있다 ,,
``` python
x = int(input())
dp = [0] * (x+1)
for i in range(2, x+1):
dp[i] = 1 + dp[i-1]
if i % 3 == 0:
dp[i] = min(dp[i], dp[i//3] + 1)
if i % 2 == 0:
dp[i] = min(dp[i], dp[i//2] + 1)
print(dp[x])
```

[BOJ] 22-10-11 (1로만들기/실버3)

---

chaeeun/SWEA/D1/아주간단한계산기.py

1938. 아주 간단한 계산기
// : 나눗셈의 몫을 가져온다!

[SWEA/D1] 22-10-11 (아주 간단한 계산기)

---

hyesu/DP/11053.py

https://www.acmicpc.net/problem/11053
DP문제의 대표적인 유형이라고 한다 ,,
하암..

[BOJ] 22-10-11 (가장 긴 증가하는 부분 수열/실버2)

---

hyesu/DP/11053.py
hyesu/DP/11055.py

https://www.acmicpc.net/problem/11055
``` python
for i in range(n):
for j in range(i):
if A[i] > A[j]:
d[i] = max(d[j] + A[i], d[i])
else:
d[i] = max(d[i], A[i])
```
이 부분에서 else를 안써서 계속 틀렸는데,
생각해보니 합을 계속 저장하는 거니까.. 꼭 있어야 한다 ^^..

[BOJ/실버2] 22-10-11 (가장 큰 증가 부분 수열)

---

hyesu/DP/11722.py

https://www.acmicpc.net/problem/11722
어제랑 비슷한 문제인데 감소한다는 점만 달라서
현재 숫자가 이전 숫자보다 작은 경우에 d를 업데이트 해줬다

[BOJ/실버2] 22-10-12 (가장 긴 감소하는 부분 순열)

---

minjung/프로그래머스/네트워크.py

[네트워크 (Programmers)](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
visit으로 확인 ->~ bfs로 돌면서 연결되있는지 확인

[Programmers] 22-10-12 (네트워크)

---

chaeeun/SWEA/D2/sample.py/백만장자프로젝트.py

1859. 백만 장자 프로젝트
어제 풀었는데 시간초과 떠서 오늘 구글링하며 해결했습니다..
핵심 : 날짜별로 차이를 계산하는 것은 맞지만
채은 풀이) 모든 차이를 다 계산하며 거기서 max 뽑아서 profit으로 더하기
정답 풀이) 뒤에서 부터 max_value를 찾고 차액 계산 + max_value 갱신!
시간초과가 날 만 했군여..

[SWEA/D2] 22-10-13 (백만장자프로젝트)

---

minjung/프로그래머스/최소직사각형.py

[최소 직사각형 [Programmers]](https://school.programmers.co.kr/learn/courses/30/lessons/86491)
가로 -> 두 변 중에서 긴부분
세로 -> 두 변 중에서 작은 부분
이라고 생각하면 엄청 쉬운데 잘못접근하면 개고생할듯 
` python 
sizes[i].sort()
x_max = max(x_max,sizes[i][0])
y_max = max(y_max,sizes[i][1])
`

[Programmers] 22-10-13 (최소 직사각형)

---

chaeyeong/문자열/14490.cpp

14490 : 백대열
https://www.acmicpc.net/problem/14490
최대공약수를 구하는 함수를 inline으로 구현
inline 키워드는 컴파일러에서 함수를 인라인 함수로 처리하도록 요청함
조금.. 빠른정도?
그래도 요즘 컴파일러는 다 알아서 처리해줘서 굳이 inline을 쓸 필요 없다지만 궁금해서 써봤다
파이썬 처럼 문자열 자를 수 없어서 ':' 위치 찾아서 문자열 잘랐다..

[BOJ/실5] 22-10-14 (백대열)

---

minjung/백준/10026.py

[[10026] 적록색약 (BOJ/Gold5)
](https://www.acmicpc.net/problem/10026)
dfs 문제 중에 구역,, 과관련된 문제가 나오면 일단 방향별로 이동하면서 가는거 생각하기
오른쪽, 아래 방향만 생각했더니 힘들엇다..
dfs로 구현했을때 런타임에러가 뜨면
`
import sys
sys.setrecursionlimit(10000) 
`
입력하기 
적록색맹, 정상인 별로 type 구분해서 코드짜는거 해보기, bfs로도 구현해보자..

[BOJ] 22-10-14 (적록색약)

---

chaeeun/SWEA/D2/sample.py/달팽이숫자.py

`1954. 달팽이 숫자`
1. 방향(델타탐색) 사용 이해 완료!
```
d_row = [0, 1, 0, -1]
d_col = [1, 0, -1, 0]
```
2. if문 안에서 조건 쓸 때의 순서도 중요하다. (순서에 따라 안 될때도 있음)
3. 2차원 배열 프린트 할 때의 포멧
```
for idx in range(lst):
print(*lst[idx])
```

[SWEA] 22-10-13 (달팽이 숫자/D2)

---

minjung/백준/7562.py

[[7562] 나이트의 이동 (BOJ/Silver1)](https://www.acmicpc.net/problem/7562)
최단경로 -> bfs 접근
dfs 로 문제를 더 많이 풀어서 dfs부터 접근햇더니 , ,
bfs 공부를 더 해야겠다.
그래프 문제에서 방향이동할땐 x,y좌표 무조건 배열에담아서 이동

[BOJ] 22-10-15 (나이트의 이동)

---

chaeeun/SWEA/D2/최빈수구하기.py

[[1204] 최빈수 구하기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV13zo1KAAACFAYh&categoryId=AV13zo1KAAACFAYh&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=1)
1. 리스트(lst) 프린트하기
`print(*lst)`
3. 리스트에서 최대값이 여러개인 경우 인덱스 찾기
리스트(lst)에서 최대값의 인덱스를 구할 때 `lst.index(max(lst))` 로 구하면 되는데
이렇게 하면 max 값이 처음으로 나온 곳의 index를 가리키므로 
같은 max 값이 여러개인 경우 원하는 인덱스값을 얻지 못할 수도 있다.
```
lst = [1, 5, 2, 5, 3]
max_value = max(lst)
max_index = [idx for idx, val in enumerate(lst) if val == max_value]
print(*max_index) # 1, 3
print(max(max_index)) # 3
```

[SWEA] 22-10-16 (최빈수 구하기/D2)

---

hyesu/DP/11057.py

https://www.acmicpc.net/problem/11057
어제 푼 문제랑 비슷하긴 한데 
이거는 맨 앞에 0이 올 수 있다.
그리고 숫자가 하나씩 차이나는게 아니라, 계속 커지기만 하면 되는 것이기 때문에
다음 dp를 구할때 만약 i번째 자리의 8 경우의수라고 하면 d[i][8] = d[i-1][8이랑 9] 이렇게 되므로, 결국 이전 자리(i-1) 자기 자신(j)부터 끝까지의 합을 항상 더해주면 된다.

[BOJ/실버1] 22-10-16 (오르막수)

---

chaeyeong/문자열/9935.cpp

boj 9935
https://www.acmicpc.net/problem/9935
음.. 그냥 문자열 잘라서 vector 로 간단히 풀 수 있는 문제였다

[Boj/골4] 22-10-16 (문자열 폭발)

---

minjung/백준/1389.py

[1389] 케빈 베이컨의 6단계 법칙(BOJ/Silver1)
2중 배열 선언 방식 
`python 
linked = [[] for _ in range(n+1)]
`

[BOJ] 22-10-17 (케빈 베이컨의 6단계 법칙)

---

chaeeun/SWEA/D2/파스칼의삼각형.py

[[2005] 파스칼의 삼각형](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5P0-h6Ak4DFAUq&categoryId=AV5P0-h6Ak4DFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=1)
<복습>
2차원 배열 초기화 후 접근하기!

[SWEA] 22-10-17 (파스칼의 삼각형/D2)

---

chaeyeong/문자열/5052.cpp

boj 5052
https://www.acmicpc.net/problem/5052
책 문제 풀이 보면서 풀었습니다..
트라이 자료구조에 문자열을 넣어서 푸는 문제

[Boj/골4] 22-10-17 (전화번호 목록)

---

hyesu/DP/2293.py

https://www.acmicpc.net/problem/2293
처음에는 아래 이미지 처럼 하면 된다고 생각해서
``` python 
import sys
input = sys.stdin.readline
n, k = map(int, input().split())
coins = []
d = [0] * (k+1)
for _ in range(n):
coins.append(int(input()))
for i in range(1, k+1):
tmp = 0
for coin in coins: 
if i == coin:
tmp += 1
elif i-coin >= 0:
tmp += d[i-coin] + 1
d[i] = tmp
print(d)
```
뭐 이런식으로 했다,, 근데 진짜 너무 큰수가 나와서 하나하나 직접 써보니까.. 2부터 틀렸음
그래서 좀 검색을 했다 (...)
점화식은 
n원을 만들 수 있는 경우의 수는 이전 행의 n원을 만들 수 있는 경우의 수 + n원에서 현재 동전 가치 (K)를 뺀 수
라서 
d[n] = d[n] + d[n-k]가 된다
혼자풀수있을까 ..? 🥺

[2293] 동전 (BOJ/골드5)

---

chaeeun/SWEA/D2/시각덧셈.py

[[1976] 시각 덧셈](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PttaaAZIDFAUq&categoryId=AV5PttaaAZIDFAUq&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=ALL&select-1=2&pageSize=10&pageIndex=2)
<복습>
`h1, m1, h2, m2 = map(int, input().split())`
하나씩 받을 때!

[SWEA] 22-10-18 (시각덧셈/D2)

---

minjung/백준/1260.py

[[1260] DFS BFS (BOJ/Silver2)
](https://www.acmicpc.net/problem/1260)
하나의 노드에 여러개의 노드가 연결될 수 있으니 이중배열이라고 단정지으면 안댐 
!!!!
len(visited[start])로 몇개의 노드랑 링크되어있는지 생각

[BOJ] 22-10-19 (DFS BFS)

---

chaeeun/SWEA/D2/중간평균값구하기.py

[[1984] 중간 평균값 구하기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5Pw_-KAdcDFAUq&categoryId=AV5Pw_-KAdcDFAUq&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=1)
1. for 반복문 이용
2. sum 함수를 이용
3. numpy 모듈 이용
4. statiscics 라이브러리 이용
`round(15.9, 0)` # 16.0
`int(round(15.3, 0))` # 15
`round(25.16, 1)` # 25.2
`round(25.163, 2)` # 25.16

[SWEA] 22-10-19 (중간 평균값 구하기/D2)

---

hyesu/DP/11727.py

https://www.acmicpc.net/problem/11727
점화식: d[n] = d[n-2]*2 + d[n-1]이고,
초깃값은 d[1] = 1, d[2] = 3이다.

[BOJ/실버3] 22-10-19 (2xn 타일링2)

---

chaeyeong/DP/2156.cpp

Boj 2156
https://www.acmicpc.net/problem/2156
완전탐색으로 풀면 2초안에 풀 수 없어서 DP로 푸는 문제

[BOJ/실1] 22-10-19 (포도주 시식)

---

hyesu/DP/10826.py

https://www.acmicpc.net/problem/10826
피보나치 -> dp로 풀면 시간 줄어든다.
점화식 i=0, 1일때 1
d[i] = d[i-1] + d[i-2]

[BOJ] 22-10-20 (피보나치 수4/실버5)

---

chaeeun/SWEA/D2/지그재그숫자.py

[[1986] 지그재그 숫자](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PxmBqAe8DFAUq&categoryId=AV5PxmBqAe8DFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=2)
나머지연산 복습!

[SWEA] 22-10-20 (지그재그숫자/D2)

---

minjung/백준/2667.py
minjung/백준/tempCodeRunnerFile.py

[[2667] 단지번호붙이기 (BOJ/Silver1)
](https://www.acmicpc.net/problem/2667)
영역구하기랑 비슷하게 풀었다
영억구하는건 BFS 를 이용하면 더 편리 
queue에 push 할때 이전 인덱스를 푸쒸해서 값이 이상하게 나왔었다
잘 확인하기

 [BOJ] 22-10-21 (단지 번호 붙이기)

---

chaeeun/BOJ/문자열/백대열.py

[[14490] 백대열](https://www.acmicpc.net/problem/14490)
< 복습 >
1. 약분은 최대공약수 이용
2. 최대 공약수 구하는 방법

[BOJ] 22-10-21 (백대열/실5)

---

jiyun/숫자/18108.py

18108 https://www.acmicpc.net/problem/18108
불기와 서기의 차이가 543년인 것을 알게되었다^_^

[18108] 1998년생인 내가 태국에서는 2541년생?! (BOJ/브론즈5)

---

chaeyeong/DP/11053.cpp

boj 11053
https://www.acmicpc.net/problem/11053
DP 문제...

[Boj/실2] 22-10-21 (가장 긴 증가하는 부분 수열)

---

minjung/백준/1012.py
minjung/백준/2667.py

[[1012] 유기농 배추(BOJ/Silver2)](https://www.acmicpc.net/problem/1012)
BFS DBS 복습

 [BOJ] 22-10-22 (유기농 배추)

---

chaeeun/SWEA/D2/숫자를정렬하자.py

[[1966] 숫자를 정렬하자](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PrmyKAWEDFAUq&categoryId=AV5PrmyKAWEDFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=3)
파이썬에서 배열 정렬 : `list.sort()`

[SWEA] 22-10-22 (숫자를 정렬하자/D2)

---

chaeyeong/DP/1520.cpp

boj 1520
https://www.acmicpc.net/problem/1520
memset으로 함수 메모리 초기화 해봄
문제는 dp 문제

[Boj/골3] 22-10-22 (내리막 길)

---

jiyun/DP/10826.py

10826 https://www.acmicpc.net/problem/10826

[10826] 피보나치 수4 (BOJ/실버5)

---

hyesu/DP/11048.py

https://www.acmicpc.net/problem/11048
N, M 에서 사탕의 최댓값인데
N, M으로 오는 경로는 (N-1, M), (N, M-1), (N-1, M-1)이다.
이 중에서 최대를 구하면 된다.
점화식: `d[i][j] = max(d[i-1][j-1], d[i][j-1], d[i-1][j]) + candy[i][j]`

[BOJ] 22-10-23 (이동하기/실버2)

---

chaeeun/SWEA/D2/조교의성적매기기.py

[[1983] 조교의 성적 매기기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PwGK6AcIDFAUq&categoryId=AV5PwGK6AcIDFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=2)
`/` 랑 `//` 차이 잘 구분하기!!!
그냥 배열 인덱스로 접근해서 풀었다.

[SWEA] 22-10-23 (조교의 성적 매기기/D2)

---

chaeyeong/연결리스트/10818.cpp

boj 10818
https://www.acmicpc.net/problem/10818

[Boj/브3] 22-10-23 (최소, 최대)

---

chaeeun/SWEA/D2/간단한소인수분해.py

[[1945] 간단한 소인수분해](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5Pl0Q6ANQDFAUq&categoryId=AV5Pl0Q6ANQDFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=3)
재귀함수를 만들어서 사용했다!!

[SWEA] 22-10-24 (간단한 소인수분해/D2)

---

minjung/백준/4936.py
minjung/백준/tempCodeRunnerFile.py

[[4963] 섬의 개수(BOJ/Silver2)](https://www.acmicpc.net/problem/4963)
일정한 조건시 break를 걸어주는 bfs 문제!

 [BOJ] 22-10-24 (섬의 개수)

---

jiyun/Bruth Force/1436.py

1435 https://www.acmicpc.net/problem/1436

[1435] 영화감독 숌(BOJ/실버5)

---

hyesu/DP/11060.py

https://www.acmicpc.net/problem/11060
하나씩 돌면서 몇개까지 뛸 수있는지 체크하고 뛸수있는 곳을 돌면서 최솟값을 구한다.
최소를 구해야 하기 때문에 첫번째로 d에 초기화 하는 수를 0이 아닌 큰 수로 해줬다. 
0으로 하면 min을 구하니까 계속 0만 나오게 된다 ..

[BOJ] 22-10-24 (점프점프/실버2)

---

chaeyeong/연결리스트/2953.cpp

boj 2953
https://www.acmicpc.net/problem/2953
연결리스트
배열은 여러 개의 데이터를 한 변수에 저장히기 위해 사용한다.. 생각하기

[Boj/브3] 22-10-25 (나는 요리사다)

---

chaeeun/SWEA/D2/쉬운거스릅돈.py

[[1970] 쉬운 거스름돈](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PsIl6AXIDFAUq&categoryId=AV5PsIl6AXIDFAUq&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=2)
거스름돈 계산할 때
남은 돈을 계산(빼기) 해주며 나눠주기~

[SWEA] 22-10-25 (쉬운 거스름돈/D2)

---

minjung/백준/2468.py
minjung/백준/tempCodeRunnerFile.py

[[2468] 안전영역 (BOJ/Silver1)](https://www.acmicpc.net/problem/2468)
조건 잘 살펴보기

 [BOJ] 22-10-26 (안전 영역)

---

chaeeun/BOJ/DP/가장긴증가하는부분수열.py

[[11053] 가장 긴 증가하는 부분수열](https://www.acmicpc.net/problem/11053)
DP(다이나믹 프로그래밍, 동적 프로그래밍) 시작!!
dp 배열을 만들어서 기억해주며 탐색하기!

[BOJ] 22-10-26 (가장 긴 증가하는 부분 수열/실2)

---

chaeyeong/스택/10828.cpp

boj 10828
https://www.acmicpc.net/problem/10828 
스택 기본 문제~

[Boj/실4] 22-10-27 (스택)

---

chaeeun/BOJ/DP/포도주시식.py

[[2156] 포도주 시식](https://www.acmicpc.net/problem/2156)
DP는 점화식을 세워서 풀기!!!

[BOJ] 22-10-27 (포도주 시식/실버1)

---

hyesu/DP/1010.py

https://www.acmicpc.net/problem/1010
왼쪽 n, 오른쪽 m일때의 경우의 수는 왼쪽 n-1, 오른쪽 m-1 ~ 끝까지
이다. 
이 문제는 같은 문제가 계속해서 나눠지기 때문에 점화식을 세워 dp로 풀면 된다

[BOJ] 22-10-28 (다리놓기/실버5)

---

minjung/백준/자료구조/10816.py

[[10816]숫자 카드 2 (BOJ/Silver4)](https://www.acmicpc.net/problem/10816)
from collections import Counter
Counter 라이브러리를 사용하면 리스트 내에서 몇번 쓰였는지 딕셔너리 형태로 계산해준다 !!

[BOJ] 22-10-28 (숫자 카드 2)

---

hyesu/DP/16359.py

https://www.acmicpc.net/problem/16395
처음에 무의식중에 배열 k만큼 만들뻔함

[BOJ] 22-10-29 (파스칼의 삼각형/실버5)

---

minjung/백준/DFS-BFS/2644.py

[[2644] 촌수계산(BOJ/Silver2)](https://www.acmicpc.net/problem/2644)
BFS 복습

[BOJ] 22-10-28 (촌수계산)

---

chaeyeong/큐/10845.cpp

boj 10845
https://www.acmicpc.net/problem/10845
.. 쉬운거 풀었어여..
큐 push , pop size, empty, front 함수를 사용해서 푸는 문제

[Boj/실4] 22-10-29 (큐)

---

minjung/백준/자료구조/17298.py

[[17298] 오큰수 (BOJ/Gold4)](https://www.acmicpc.net/problem/17298)
이중 for 문 사용하면 시간초과뜸
오큰수를 찾지 못한 배열의 인덱스를 저장하는 stack을 만들어서 오큰수를 찾으면 Pop

[BOJ] 22-10-29 (오큰수)

---

chaeeun/BOJ/Queue/큐.py

[BOJ] 22-10-29 (큐/실버4)

---

soyoon/11726.py

[11726] https://www.acmicpc.net/problem/11726
최적 알고리즘 구조와 중복 부분이 있으면 동적 프로그래밍을 이용하자

[11726] 2xn 타일

---

soyoon/2156.py

[2156], https://www.acmicpc.net/problem/2156
선택할 수 있는 연속 사건 수(이 문제의 경우 3개)가 정해져있을 때 각각 경우의수
1. 해당 순서의 포도주를 마시는 경우 
1.1 이전 순서의 포도주를 마신 경우 - w[i] + w[i-1] + dp[i-3]
1.2 이전 순서의 포도주를 마시지 않은 경우 - w[i] + dp[i-2]
2. 해당 순서의 포도주를 마시지 않는 경우
dp[i-1]
를 비교하여 최대값을 더하는 동적 프로그래밍 ~

[2156] 포도주 시식

---

chaeeun/BOJ/스택/스택.py

[[10828] 스택](https://www.acmicpc.net/problem/10828)
stack 배열 선언 시 for 문 밖에서 선언 해야 한다.
어제도 이거때매 틀릴뻔했는데 오늘도 똑같이 했다가 발견

[BOJ] 22-10-30 (스택/실버4)

---

minjung/백준/DFS-BFS/7569.py

[[7569] 토마토 (BOJ/Gold5)](https://www.acmicpc.net/problem/7569)
BFS 복습 , 기존 토마토 문제 2차원 배열에서 3차원 배열로 확장한 문제

[BOJ] 22-10-30 (토마토)

---

hyesu/정렬/10876.Py

https://www.acmicpc.net/problem/10867
set을 이용하면 중복을 제거할 수 있다.
근데 set은 리스트가 아니라서 리스트 메서드를 쓸 수 없으니 list로 감싸서 다시 리스트로 바꿔준다.

[BOJ] 22-10-30 (중복 뺴고 정렬하기/실버5)

---

soyoon/11719.py
soyoon/2156.py

[11719] https://www.acmicpc.net/problem/11719
파이썬에서는 EOF까지 sys.stdin.read()로 여러줄을 입력받을 수 있다

[11719] 그대로 출력하기2

---

minjung/백준/이분탐색/1654.py

[[1654] 랜선 자르기 (BOJ/Silver2)](https://www.acmicpc.net/problem/1654)
최대 값을 찾는 Parametic search 문제.
랜선의 개수가 n개 이상일때도 N개로 생각하고, 랜선길이의 최댓값을 구하는 문제
total 랜선길이의 개수  >= N 이면 무조건 return mid를 해주었는데 
바로 리턴하지 말고 result에 저장한다음에 
끝까지 돌아간 후에 result 값을 리턴해야함 
조건 주의 !

[BOJ] 22-10-31 (랜선 자르기) 

---

hyesu/정렬/11728.py

https://www.acmicpc.net/problem/11728
바보처럼 중복 제거하라는 말도 안했는데 set해서 두번틀림

[BOJ] 22-10-31 (배열합치기/실버5)

---

jiyun/Bruth Force/2003.py

2003 https://www.acmicpc.net/problem/2003

[2003] 수들의 합 2(boj/실버4)

---

hyesu/정렬/11004.py

https://www.acmicpc.net/problem/11004
생각보다 시간이..길다
왤까..

[BOJ] 22-11-02 (K번쨰 수/실버5)

---

chaeeun/BOJ/완전탐색/부분수열의합.py

[[1182] 부분수열의 합](https://www.acmicpc.net/problem/1182)
조합 쓰고 싶을 땐 다음과 같이 하면 된다.
```
import itertools
nCr = itertools.combinations(lst, num) # 리스트(lst)에서 원하는 수(num) 만큼 뽑기
```
뽑힌 nCr에서 하나씩 접근하기 위해서는 다음과 같이 하면 된다.
```
for num in nCr:
print(num)
```

[BOJ] 22-11-02 (부분수열의 합/실버2)

---

jiyun/Bruth Force/14501.py

14501 퇴사 https://www.acmicpc.net/problem/14501
dp + 브루트포스

[14501] 퇴사

---

chaeeun/BOJ/브루트포스/영화감독숌.py

[[1436] 영화감독 숌](https://www.acmicpc.net/problem/1436)
숫자를 문자열로 : `str(num)`
문자열 안에 원하는 문자(열)이 있는지 확인하는 법 : `if '666' in str(num):
`

[BOJ] 22-11-03 (영화감독 숌/실버5)

---

soyoon/14502.py

[1541], https://www.acmicpc.net/problem/1541

[1541] 잃어버린 괄호

---

chaeeun/SWEA/D2/패턴마디의길이.py

[2007] 패턴 마디의 길이
문자열 안에 원하는 문자열 있는지 찾는 방법
`if str[0:i] in str:`

[SWEA] 22-11-04 (패턴 마디의 길이/D2)

---

minjung/백준/이분탐색/2110.py

[[2110] 공유기 설치 (BOJ/Gold4)](https://www.acmicpc.net/problem/2110)
뭘 잡고 이분탐색으로 돌려야 할지 어려움..
결과적응로 집 사이사이 최대 길이 값을 기준으로 이분탐색을 돌려야 함 
mid 값보다 거리가 클경우 cnt+1로 c만큼 판단 ,  그리고 최댓값이 되니까 그 값도 저장

[BOJ] 22-11-04 (공유기 설치/Gold4)

---

minjung/백준/DFS-BFS/1697.py

[[1697] 숨바꼭질 (BOJ/Silver1)](https://www.acmicpc.net/problem/1697)
BFS 복습

[BOJ] 22-11-04 (숨바꼭질/Silver1)

---

soyoon/1541.py
soyoon/4949.py

[4949], https://www.acmicpc.net/problem/4949
짝이 맞으면 pop해서 해결하는 문제는 조건문에 "()", "[]" 처럼 쌍으로 받지 말고 "(" , "[" 이렇게 받자

[4949] 균형잡힌 세상

---

jiyun/백트래킹/15650.py

15650 https://www.acmicpc.net/problem/15650
백트래킹!

[15650] n과 m(2) (BOJ/Silver3)

---

chaeyeong/큐/2164.cpp

boj 2164
https://www.acmicpc.net/problem/2164
큐 활용 문제

[BOJ] 22-11-04 (카드2/실4)

---

hyesu/정렬/11931.py

https://www.acmicpc.net/problem/11931
sort reverse!

[BOJ] 22-11-04 (수 정렬하기4/실버5)

---

jiyun/백트래킹/15650.py
jiyun/백트래킹/15651.py

15651 https://www.acmicpc.net/problem/15651
백트래킹 고수가 되자

[15651] n과 m(3)(BOJ/Silver3)

---

chaeeun/SWEA/D2/파리퇴치.py

[[2001] 파리퇴치](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PzOCKAigDFAUq&categoryId=AV5PzOCKAigDFAUq&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=1)
몇 주 전에 시도했다가 못풀겠어서 포기했었는데 오늘 20분만에 풀었다!!
그냥 배열에 반복문으로 돌려가며 <범위 조심해서> 더해주면 됐다!

[2001] 파리퇴치

---

soyoon/1764.py
soyoon/4949.py

[1764], https://www.acmicpc.net/problem/1764
array를 사용했더니 시간초과가 났다 ->
공통부분을 구해야 하므로 데이터타입 집합(set)의 교집합(&)을 사용!

[1764] 듣보잡

---

minjung/백준/이분탐색/1300.py

[[1300]k번째 수 (BOJ/Gold2)](https://www.acmicpc.net/problem/1300)
아이디어 생각해내기가 어려움. 이걸 이분탐색으로 ?
k번째 수를 구하는거니까 max를 K 로 잡고 이분탐색 돌려서 cnt 가 k 일때 저장

[BOJ] 22-11-05 (k번째 수/Gold3)

---

chaeeun/SWEA/D2/초심자의회문검사.py

[[1989] 초심자의 회문 검사](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PyTLqAf4DFAUq&categoryId=AV5PyTLqAf4DFAUq&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=1)
데칼코마니 문자열 찾는 문제였다.
배열 인덱스 접근할때
[i] 랑 [k-i] 로 접근하면
(i) + (k - i) = k
이런 규칙이 있는 인덱스들에 접근할 수 있다.

[1989] 초심자의 회문 검사

---

soyoon/9251.py

[9251], https://www.acmicpc.net/problem/9251
1. 입력 내용이 길면 read = sys.stdin.readline 로 입력받는 게 실행시간 단축
2. 줄 단위로 입력받고 싶을 땐 str1, str2 = read().strip(), read().strip()
3. 2개의 문자열을 순회하면서 검색하고 싶을 때 2차원 배열을 만들어서 동적프로그래밍 사용 (바로 전 단계와 비교)

[9251] LCS

---

jiyun/백트래킹/15652.py

[15652] n과m(4)(BOJ/Silver3)

---

hyesu/정렬/1181.py

https://www.acmicpc.net/problem/1181
문자열, 정렬
이 문제에서 정렬조건은 아래와 같다.
``` python
words.sort()
words.sort(key=len)
```
하위 정렬 조건을 먼저, 이후 상위 정렬 조건을 이용해 정렬한다.
readline은 개행문자까지 함께 입력된다.
따라서 아래와 같이 rstrip을 해준다.
``` python
import sys
input = sys.stdin.readline
words = []
n = int(input())
for _ in range(n):
words.append(input().rstrip())
```

[BOJ] 22-11-06 (단어 정렬/실버5)

---

soyoon/1259.py

[1259], https://www.acmicpc.net/problem/1259
for문 정의할 때 범위에서 range를 빼먹지 말자^^

[1259] 팰린드롬수

---

chaeeun/SWEA/D3/일요일.py

[[13229] 일요일](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AX0SaDW6L2oDFASs&categoryId=AX0SaDW6L2oDFASs&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=2)
리스트에서 원하는 원소의 인덱스 찾고 싶을 때
`lst.index('원하는 값')`

[SWEA] 22-11-07 (일요일/D3)

---

minjung/백준/DFS-BFS/16236.py

[[16236] 아기 상어(BOJ/Gold3)](https://www.acmicpc.net/problem/16236)
BFS 에 여러가지 조건이 추가된 문제 먹이를 먹는 순서를 sort로 고려해야 함 + 아기 상어의 몸집 크기도 고려해야 함 나중에 다시 보기

[BOJ] 22-11-07 (아기 상어/Gold3)

---

jiyun/백트래킹/15649.py

[15649] n과m(BOJ/Silver3)

---

chaeyeong/BFS/1697.cpp

boj 1697
https://www.acmicpc.net/problem/1697

[Boj] 22-11-07 (숨바꼭질/실1)

---

jiyun/DP/1003.py

1003 https://www.acmicpc.net/problem/1003

[1003] 피보나치 함수(BOJ/Silver3)

---

chaeeun/SWEA/D3/알파벳공부.py

[15230] 알파벳 공부
--
[[15230] 알파벳 공부](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AYLnMQT6vPADFATf&categoryId=AYLnMQT6vPADFATf&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=JAVA&select-1=3&pageSize=10&pageIndex=1&&&&&&&&&&)
1. 그냥 엔터 입력하면 `strr=input()` 으로 아무것도 안 들어가므로
입력됐다고 생각하고 `strr[0]` 으로 접근하면 안된다!!!!!!..
2. (복습) 알파벳 숫자로 계산하기 : `ord('A')`

[15230] 알파벳 공부

---

chaeyeong/BFS/2178.cpp

boj 2178
https://www.acmicpc.net/problem/2178

[Boj] 22-11-08 (미로 탐색/실1)

---

minjung/백준/DFS-BFS/2252.py

[[2252] 줄 세우기(BOJ/Gold3)](https://www.acmicpc.net/problem/2252)
위상정렬 이용하여 푸는 문제 
1 2 아렇게 들어오면 2는 무조건 1뒤여야 하므로 degree값 ++

[BOJ] 22-11-08 (2252/Gold3)

---

soyoon/9093.py

[9093], https://www.acmicpc.net/problem/9093
1. input().split(' ')은 자동으로 문자열로 반환된다
2. 줄바꿈 없이 프린트하고 싶을 땐 print(, end=' ')

[9093] 단어 뒤집기

---

minjung/백준/다이나믹 프로그래밍/2775.py
minjung/백준/다이나믹 프로그래밍/tempCodeRunnerFile.py

[[2775] 부녀회장이 될테야(BOJ/Bronze1)](https://www.acmicpc.net/problem/2775)
dp 문제!
그냥 2차원배열로만 생각했는데 1차원배열로도 게속 업뎃해주면 된다

[BOJ] 22-11-09 (2275/Bronze1)

---

chaeeun/SWEA/D3/통나무자르기.py

[[14692] 통나무 자르기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AYJW0g-qlO8DFASv&categoryId=AYJW0g-qlO8DFASv&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=1)
D3이지만 엄청 쉬운 문제였다

[14692] 통나무 자르기

---

hyesu/그리디/18310.py

https://www.acmicpc.net/problem/18310
그리디
정렬 후 가운데 집을 선택하면 된다
짝수인 경우와 홀수인 경우가 다르니까 이 둘을 통합할 수 있는건 (n-1)//2이다

[BOJ] 22-11-09 (안테나/실버3)

---

soyoon/11399.py
soyoon/5430.py

[11399], https://www.acmicpc.net/problem/11399
누적값의 합은
for i in range(n):
for j in range(I+1):
로 계산하자

[11399] ATM

---

jiyun/DP/11727.py

[11727] 2xn 타일링(2)(BOJ/Silver3)

---

chaeeun/SWEA/D3/24시간.py

[[12367] 24시간](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AXsEBlLqedsDFARX&categoryId=AXsEBlLqedsDFARX&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=2)
(복습) 24시간제 계산

[SWEA] 22-11-10 (24시간/D3)

---

hyesu/DP/10211.py

https://www.acmicpc.net/problem/10211
DP
이전것 + 현재, 현재 중 큰 값을 배열에 저장한다.
연속하는 것 중 최대값이므로 위의 값을 저정한 값 중 가장 큰 값을 출력한다.

[BOJ] 22-11-10 (Maximum Subarray/실버4)

---

chaeeun/SWEA/D3/숫자조작.py

[[13428] 숫자 조작](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AX4EJPs68IkDFARe&categoryId=AX4EJPs68IkDFARe&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=1)
- 숫자로 이루어져있는 리스트를 하나의 숫자로 나타내고 싶을 때
`''.join(map(str, lst))`

[SWEA] 22-11-11 (숫자 조작/D3)

---

minjung/백준/다이나믹 프로그래밍/10844.py

[[10844]쉬운 계단 수(BOJ/Silver1)](https://www.acmicpc.net/problem/10844)
케이스 잘 나누기 
앞에 1~8 일때는 뒤에 2 숫자가 올 수있고
0,9일때는 뒤에 한가지 숫자만 올 수 있음

[BOJ] 22-11-11 (쉬운계단 수/Silver1)

---

jiyun/DP/1149.py

[1149] RGB거리 (BOJ/Silver1)

---

soyoon/1931.py

[1931], https://www.acmicpc.net/problem/1931
2차원 배열에서 열 기준으로 정렬: .sort(key=lambda x:(x[1], x[0]))

[1931] 회의실 배정

---

hyesu/그리디/9237.py

https://www.acmicpc.net/problem/9237
그리디
가장 긴걸 가장 먼저 심으면 된다
나무 하나당 하루가 걸리므로 해당만큼 날짜를 더해준다.
첫날이 1일이므로, 마지막 출력에 1을 더한다.

[BOJ] 22-11-11 (이장님 초대/실버5)

---

chaeeun/SWEA/D3/간단한압축풀기.py

[[1946] 간단한 압축 풀기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=2&contestProbId=AV5PmkDKAOMDFAUq&categoryId=AV5PmkDKAOMDFAUq&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=2&pageSize=10&pageIndex=2)
- 다음 테스트 케이스 받을때 엔터 안된상태로 받아도 틀린걸로 뜸 ㅠ
- 안풀릴땐 다른거 하며 환기시키고 와서 다른 방향으로 생각해보기!

[SWEA] 22-11-12 (간단한 압축풀기/D3)

---

jiyun/DP/1932.py

[1932] 정수 삼각형(BOJ/Silver1)

---

soyoon/11047.py

[11047], https://www.acmicpc.net/problem/11047
<continue문>
for문에서 조건을 만족할 때 다음 반복수로 넘어가고 싶을 때 사용하자..

[11047] 동전 0

---

minjung/백준/다이나믹 프로그래밍/9461.py

[[9461] 파도반 수열(BOJ/Silver3)](https://www.acmicpc.net/problem/9461)
점화식 세워서 푸는 문제
배열값 자체를 초기에 정해줘야 인덱스 에러 안남

[BOJ] 22-11-12 (파도반 수열/Silver3)

---

chaeyeong/BFS/10026.cpp

boj 10026
https://www.acmicpc.net/problem/10026

[Boj] 22-11-12 (적록색약/골5)

---

minjung/백준/다이나믹 프로그래밍/2156.py

[2156] 포도주 시식(BOJ/Silver1)
점화식세우기 ! 
연속 3번 안되서 조건걸어서 max 값 취하기

[BOJ] 22-11-13 (포도주 시식/Silver1)

---

chaeeun/SWEA/D3/외로운문자.py

[[10912] 외로운 문자](https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AXVJuEvqLAADFASe)
- 파이썬 실행시 이렇게도 가능하다!
```
def code():
if __name__ == '__main__':
code()
```
- 스택의 구조를 활용한 리스트!

[SWEA] 22-11-13 (외로운 문자/D3)

---

soyoon/11047.py
soyoon/1931.py
soyoon/2743.py

[2743], https://www.acmicpc.net/problem/2743
.

[2743] 단어 길이 재기

---

chaeeun/SWEA/D3/문자열의거울상.py

[[10804] 문자열의 거울상](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AXTC0x16D8EDFASe&categoryId=AXTC0x16D8EDFASe&categoryType=CODE&problemTitle=&orderBy=FIRST_REG_DATETIME&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=3)
문제에 반영하지는 않았지만 아래처럼 하면 문자열에서 원하는 문자만 바꿀 수 있다.
```
strr = 'abcd'
strr = strr.replace('a', 'z') # 이렇게 해줘야 함!
print(strr)
```

[10804] 문자열의 거울상

---

soyoon/5988.py

[5988], https://www.acmicpc.net/problem/5988

[5899] 홀수일까 짝수일까

---

minjung/백준/다이나믹 프로그래밍/14501.py

[[14501] 퇴사 (BOJ/Silver3)](https://www.acmicpc.net/problem/14501)
뒤에서부터 dp를 도는게 핵심
1. i번째 일을 할때의 이익 ( = i번째 일의 이익 + i 번째 일을 하는데 걸리는 시간 후의 이익) : 
2. i번쨰 일을 건너뛰고 i+1 번쨰 일을 할때의 이익 
둘 중에 큰 값으로 갱신해줌 뒤에서부터

[BOJ] 22-11-14 (퇴사/Silver3)

---

chaeyeong/BFS/4178.cpp

boj 4178
https://www.acmicpc.net/problem/4179

[Boj] 22-11-14 (불!/골4)

---

hyesu/정렬/11651.py

https://www.acmicpc.net/problem/11651
정렬
data.sort(key=lambda x: (x[1], x[0]))
정렬할때 lamda 쓰면 조건을 이용할 수 있음

[BOJ] 22-11-14 (좌표 정렬하기2/실버5)

---

jiyun/DP/11722.py

[11722] 가장 긴 감소하는 부분 수열(BOJ/Silver2)

---

chaeeun/SWEA/D3/sum.py

[[1209] sum](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV13_BWKACUCFAYh&categoryId=AV13_BWKACUCFAYh&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=1)
- 배열 입력받을 때 ➡️ # 2 로 하는게 더 좋을듯!
```
lst = []
for _ in range(100):
lst.append(map(int, input().split()))
```
```
lst = [list(map(int, input().split())) for _ in range(N)]
```
- 좌하향 대각선 합 구할 때
i + j 의 값이 100`-1` 이어야 함!! (인덱스는 0부터 시작하므로)

[SWEA] 22-11-15 (sum/D3)

---

soyoon/1212.py

[1212], https://www.acmicpc.net/problem/1212
파이썬에서는 정수를 8진수로 입력받는 함수가 내장되어 있다. ( int(input(), 8) )
이후 bin()으로 감싸주면 2진수가 되고 2진수로 변환한 후에는 0b가 붙으므로 2번째 인덱스부터 출력한다

[1212] 8진수 2진수

---

minjung/백준/다이나믹 프로그래밍/1010.py

[[1010] 다리 놓기(BOJ/Silver5)](https://www.acmicpc.net/problem/1010)
조합으로 푸는 문제 
공식만 알면 괜찮음
파이썬엔 math에 내장 모듈 팩토리얼이 있긴하다
math.factorial(n)

[BOJ] 22-11-15 (다리 놓기/Silver5)

---

chaeeun/SWEA/D3/민석이의과제체크하기.py

[[5431] 민석이의 과제 체크하기](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AWVl3rWKDBYDFAXm&categoryId=AWVl3rWKDBYDFAXm&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=3)
`[]` 말고 그냥 `list()` 로 감싸자!
ex) `lst = list(map(int, input().split()))`

[5431] 민석이의 과제 체크하기

---

soyoon/1212.py

[11656], https://www.acmicpc.net/problem/11656

[11646] 접미사 배열

---

chaeyeong/BFS/1012.cpp

boj 1012
https://www.acmicpc.net/problem/1012

[Boj] 22-11-16 (유기농 배추/실2)

---

chaeeun/SWEA/D3/부분수열의합.py

[[2817] 부분 수열의 합](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV7IzvG6EksDFAXB&categoryId=AV7IzvG6EksDFAXB&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=1&&&&&&&&&&)
재귀로!!!! dfs

[SWEA] 22-11-17 (부분 수열의 합/D3)

---

soyoon/10844.py

[10844], https://www.acmicpc.net/problem/10844
앞뒤에 어떤 숫자가 오느냐에 따라서 다음 단계의 경우의 수가 달라지므로 표에서 [i-1][j-1], [i-1][j+1] 값을 이용한다

[10844] 쉬운 계단수

---

minjung/백준/다이나믹 프로그래밍/11052.py

[BOJ] 22-11-18 (카드 구매하기/Silver1)

---

chaeeun/SWEA/D3/거듭제곱.py

[[1217] 거듭 제곱](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV14dUIaAAUCFAYD&categoryId=AV14dUIaAAUCFAYD&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=3)
재귀함수 구현! 복습

[SWEA] 22-11-18 (거듭 제곱/D3)

---

minjung/백준/정렬/10817.py

[BOJ] 22-11-18 (세 수/BOJ)

---

chaeeun/SWEA/D3/태혁이의사랑은타이밍.py

[[4299] 태혁이의 사랑은 타이밍](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AWLv6mx6htoDFAVV&categoryId=AWLv6mx6htoDFAVV&categoryType=CODE&problemTitle=&orderBy=RECOMMEND_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=4)
날짜, 시간, 분 -> 다 분으로 맞추기!

[4299] 태혁이의 사랑은 타이밍

---

soyoon/11656.py

[10953], https://www.acmicpc.net/problem/10953

[10953] A + B - 6

---

chaeeun/SWEA/D3/String.py

[[1213] String](https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=3&contestProbId=AV14P0c6AAUCFAYi&categoryId=AV14P0c6AAUCFAYi&categoryType=CODE&problemTitle=&orderBy=INQUERY_COUNT&selectCodeLang=PYTHON&select-1=3&pageSize=10&pageIndex=1)
- 배열 인덱스 조심
- for if 남발하지 말고 로직을 세워서 풀기!!!!!!!!!
(안풀릴땐 다시 종이에 써가면서 풀자)

[SWEA] 22-11-20 (String/D3)

---

soyoon/10953.py

[14425], https://www.acmicpc.net/problem/14425

[14425] 문자열 집합

---

minjung/프로그래머스/완전탐색/카펫.py

카펫 (Programmers/Level2)
사각형의 넓이 이용 !
카펫의 개수 == 가로* 세로 인데
모양이 정해져있으니 그것을 고려해서 알아내면 댐

[Programmers] 22- 11-22 (카펫)

---

minjung/프로그래머스/다이나믹프로그래밍/정수삼각형.py

정수삼각형 (Programmers/Level2)
dp 문제 하나의 점에서 어느 방향으로 나갈지 잘 생각하고
최대값을 리턴하면된다

[Programmers] 22-11-22 (정수삼각형)

---

chaeeun/KAKAO/신규아이디추천.py

[[72410] 신규 아이디 추천](https://school.programmers.co.kr/learn/courses/30/lessons/72410)
- 문자열 관련 함수 : `strip()`

[Programmers] 22-11-22 (신규 아이디 추천/Lv1)

---

minjung/백준/다이나믹 프로그래밍/9465.py
minjung/프로그래머스/완전탐색/카펫.py

[[9465] 스티커 (BOJ/Silver1)](https://www.acmicpc.net/problem/9465)
점화식까진 생각했는데
어느 부분에서 max를 적용하는지 생각하기 좀 힘들었음

[BOJ] 22-11-24 (스티커)

---

chaeeun/Programmers/level1/성격유형검사하기.py

[[118666] 성격 유형 검사하기](https://school.programmers.co.kr/learn/courses/30/lessons/118666)
dictionary 이용~~ 복습

[Programmers] 22-11-25 (성격 유형 검사하기/Lv1)

---

minjung/백준/다이나믹 프로그래밍/2133.py

[[2133] 타일 채우기 (BOJ/Gold4)](https://www.acmicpc.net/problem/2133)
점화식 세우기 연습 더 해야할듯 
타일 채우기 -> 전체 면적넓이로 접근 !
변의 길이가 6일 때는 4일때하고 나머지 부분 채우기 등등 다 해보고 점화식 세우기
dp[4]-> dp[2]*dp[2]+2 = 11
dp[6] -> dp[4]*dp[2]+dp[2]*2+2 = 41
dp[8] -> dp[6]*dp[2] +dp[4]*2 +dp[2]*2+2

[BOJ] 22-11-25 (타일 채우기/Gold4)

---

minjung/백준/다이나믹 프로그래밍/11048.py

[[11048] 이동하기 (BOJ/Silver2)](https://www.acmicpc.net/problem/11048)
흔한 dp 문제! 직접 해보면 풀 수 있는 정도 였다
점화식 세울때 고려해야할 조건(방향)이 세 방향이였는데 두방향으로 줄여서 생각하면 된다

[BOJ] 22-11-26 (이동하기/Silver2)

---

minjung/백준/다이나믹 프로그래밍/2565.py

[[2565] 전깃줄 (BOJ/Gold5)](https://www.acmicpc.net/problem/2565)
그냥 코드 짜고 테스트 케이스 돌렸을 떄 잘 돌아갔는데 제출하니까 틀림. 
가장 긴 증가 수열 알고리즘이용하는 문제 -> 알고리즘을 나중에 따로 공부해야할듯 
좌표 값 비교해서 겹치는 부분 찾는 코드는 같은데 [0]인덱스 기준으로 먼저 소팅해준 다음 [1]비교하는게 좋은 아이디어인듯 
왜 전체 - Max(dp)인지는 애매하게 이해가 된다

[BOJ] 22-11-27 (전깃줄/Gold5)

---

chaeeun/Programmers/Lv3/합승택시요금.py

[[72413] 합승 택시 요금](https://school.programmers.co.kr/learn/courses/30/lessons/72413)
- Dijkstra 알고리즘
- Floyd-Warshall 알고리즘 (다익스트라 응용버전)

[72413] 합승 택시 요금

---

chaeeun/BOJ/정렬/수정렬하기3.py

[[10989] 수 정렬하기3](https://www.acmicpc.net/problem/10989)
- 입력 받을때
`input()` 보다는 `import sys` `sys.stdin.readline()` 이걸로 하기 (시간초과..)
- sort()로 하지 말고 다른 방식으로 접근
이미 0으로 가득찬 배열 만들고 거기에 숫자를 입력받는게 아니라 받은 숫자의 인덱스에 +=1  해주기
1 이상인 것들은 그 인덱스를 입력받은 값 만큼 출력하기

[BOJ] 22-11-28 (수 정렬하기3/Bronze5)

---

minjung/백준/다이나믹 프로그래밍/2225.py

[[2225]분해합(BOJ/Gold5)](https://www.acmicpc.net/problem/2225)
직접 n=1....k=3 까지 풀고 dp를 이중배열로 보면 점화식을 알 수 있다.
해보면 엄청 어렵진 않은데 이게 dp문제인지 수학문제인지  파악하는게 중요할듯

[BOJ] 22-11-29 (분해합/Gold5)

---

chaeeun/BOJ/수학/귀여운수.py

[[17294] 귀여운 수~ε٩(๑> ₃ <)۶з](https://www.acmicpc.net/problem/17294)
플래그 변수 잘 활용하기

[17294] 귀여운 수~ε٩(๑> ₃ <)۶з

---

minjung/백준/다이나믹 프로그래밍/1309.py

[[1309] 동물원 (BOJ/Silver1)](https://www.acmicpc.net/problem/1309)
경우의 수를 나누어 계산 
1. 사자가 왼쪽에 있는 경우
2. 사자가 오른쪽에 있는 경우
3. 사자가 없는 경우 
나누어 생각하면 패턴 있음

[BOJ]22-12-01  (동물원/Silver1)

---

chaeeun/BOJ/정렬/단어정렬.py

[[1181] 단어 정렬](https://www.acmicpc.net/problem/1181)
- list를 set()으로 바꾸는 방법
```
lst = list()
sett = set()
new_lst = list(map(set, lst))
```
- list()를 set()으로 바꾸면
중복은 사라지지만, 순서가 뒤죽박죽이 되어버린다

[BOJ] 22-12-01 (단어 정렬/Silver5)

---

minjung/백준/DFS-BFS/1916.py
minjung/백준/DFS-BFS/tempCodeRunnerFile.py

[[1916] 최소 비용 구하기(BOJ/Gold5)](https://www.acmicpc.net/problem/1916)
오랜만에 그래프 문제 복습하기
다시 보기
풀이는 대부분  큐가 아니라 힙큐를 많이 이용했음!
다익스트라 알고리즘 다시 공부

[BOJ] 22-12-02 (최소 비용 구하기/Gold5)

---

chaeeun/BOJ/DP/연속합.py
chaeeun/BOJ/완전탐색/부분수열의합.py
chaeeun/SWEA/D2/패턴마디의길이.py
chaeeun/SWEA/D3/알파벳공부.py

[[1912] 연속합](https://www.acmicpc.net/problem/1912)
- DP!!!!!
`dp = []` 배열 만들어서 메모이제이션 해주기.
숫자 갱신하며!!

[BOJ] 22-12-02 (연속합/Silver2)

---

minjung/프로그래머스/보석쇼핑.py

[보석 쇼핑 (Programmers/Level3)](https://school.programmers.co.kr/learn/courses/30/lessons/67258)
투 포인터 사용하는 아이디어 잘 생각
나중에 다시 보기

[Programmers] 22-12-03 (보석 쇼핑/Level3)

---

chaeeun/Programmers/Lv3/보석쇼핑.py

[[67258] 보석 쇼핑](https://school.programmers.co.kr/learn/courses/30/lessons/67258)
- 투포인터

[67258] 보석 쇼핑

---

chaeeun/BOJ/그리디/설탕배달.py

[[2839] 설탕배달](https://www.acmicpc.net/problem/2839)
- 그리디로 풀 수 있었다!!

[BOJ] 22-12-04 (설탕배달/Silver4)

---

chaeeun/BOJ/문자열/크로아티아문자열.py

[[2941] 크로아티아 알파벳](https://www.acmicpc.net/problem/2941)
- replace 함수..복습
replace함수 써볼 생각은 했지만 이렇게 쓰는거는 참신한것 같다...
다양한 각도로 생각해볼것!!!!!

[BOJ] 22-12-06 (크로아티아 알파벳/Silver5)

---

chaeeun/BOJ/브루트포스/덩치.py

[[7568] 덩치](https://www.acmicpc.net/problem/7568)
(참고)
완전탐색까지는 맞게 접근했는데
더 복잡한 생각 대신 그때그때 비교해서 rank로 더해주면 됐었다!!..

[BOJ] 22-12-11 (덩치/Silver5)

---

minjung/백준/DFS-BFS/1922.py

[1922] 네트워크 연결(BOJ/Gold4)
런타임 에러 수정

[1922] 네트워크 연결(BOJ/Gold4) (런타임 에러 수정)

---

chaeeun/BOJ/브루트포스/숫자빈도수.py

[[14912] 숫자 빈도수](https://www.acmicpc.net/problem/14912)
시간초과를 항상 조심하자

[14912] 숫자 빈도수

---

chaeeun/BOJ/자료구조/수찾기.py

[[1920] 수 찾기](https://www.acmicpc.net/problem/1920)
- 집합 자료형을 통한 포함 여부 확인!!!
이전에 틀렸던 문제였는데
자료형을 list에셔 set으로 바꿔줬더니 풀렸다!!

[1920] 수 찾기

---

chaeeun/Programmers/Lv1/문자열 내 p와 y의 개수.js

[[12916] 문자열 내 p와 y의 개수](https://school.programmers.co.kr/learn/courses/30/lessons/12916?language=javascript)
- 문자열 내 `match()`
- 정규표현식 `/p/gi` `/y/gi`
- 문자열 내 `includes()`
- if문 범위의 중요성

[Programmers] 22-12-15 (문자열 내 p와 y의 개수/Lv1)

---

chaeeun/Programmers/Lv2/최댓값과 최솟값.js

[[12939] 최댓값과 최솟값](https://school.programmers.co.kr/learn/courses/30/lessons/12916?language=javascript)
- 문자열로 이루어진 배열을 숫자로 바꾸기
`s_arr.map(x => parseInt(x))`
- 배열에서 최소/최대 값 구하기
`Math.min(...s_arr)`
`Math.max(...s_arr)`

[Programmers] 22-12-15 (최댓값과 최솟값/Lv2)

---

chaeeun/Programmers/Lv2/최솟값 만들기.js

[[12941] 최솟값 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/12941#)
- 숫자 배열 정렬하는법
- 이 문제는 최소*최대 들을 더해가면 됐다.

[Programmers] 22-12-16 (최솟값 만들기/Lv2)

---

chaeeun/Programmers/Lv2/카펫.js

[[42842] 카펫](https://school.programmers.co.kr/learn/courses/30/lessons/42842)
- 약수 구하기 복습!!

[Programmers] 22-12-16 (카펫/Lv2)

---

chaeeun/Programmers/Lv2/짝지어 제거하기.js

[[12973] 짝지어 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12973)
- 스택 복습!!!

[Programmers] 22-12-17 (짝지어 제거하기/Lv2)

---

minjung/백준/DFS-BFS/1197.py

[1197] 최소 스패닝 트리(BOJ/Gold4)
최소 스패닝 기본 문제 !!
복습하기

[BOJ] 22-12-18 (최소 스패닝 트리/Gold4)

---

chaeeun/Programmers/Lv2/괄호 회전하기.js

[[76502] 괄호 회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/76502)
- 스택 복습
종류가 여러개인 것들로 스택 이용하는 경우!

[Programmers] 22-12-18 (괄호 회전하기/Lv2)

---

chaeeun/Programmers/Lv1/두 정수 사이의 합.js

[[12912] 두 정수 사이의 합](https://school.programmers.co.kr/learn/courses/30/lessons/12912)
작은수부터 더해가므로
a랑 b중에 뭐가 더 작은지 체크 하고 더하기

[12912] 두 정수 사이의 합

---

chaeeun/Programmers/Lv1/나머지가 1이 되는 수 찾기.js

[[87389] 나머지가 1이 되는 수 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/87389)
-

[Programmers] 22-12-20 (나머지가 1이 되는 수 찾기/Lv1)

---

chaeeun/BOJ/그래프/DFS와 BFS.py

[[1260] DFS와 BFS](https://www.acmicpc.net/problem/1260)
- `그래프`
2차원 배열 초기화 한 후 연결된 곳 1로 표시 (인덱스를 노드 번호로)
- `DFS`
재귀
- `BFS`
큐

[BOJ] 22-12-21 (DFS와 BFS/Silver2)

---

chaeeun/BOJ/그래프/점프왕쩰리.py

[[16173] 점프왕 쩰리](https://www.acmicpc.net/problem/16173)
2차원 배열에서의 `BFS` !!

[BOJ] 22-12-23 (점프왕 쩰리/Silver4)

---

chaeeun/BOJ/그래프/연결요소의개수.py

[[11724] 연결 요소의 개수](https://www.acmicpc.net/problem/11724)
- 연결된 그래프들의 뭉탱이 개수 찾는 유형 처음 풀어봤다!
- input 받을 때 `sys`로 받자!!!!!
```
import sys
sys.stdin.readline()
```

[11724] 연결 요소의 개수

---

chaeeun/Programmers/Lv1/핸드폰번호가리기.py

[[12948] 핸드폰 번호 가리기](https://school.programmers.co.kr/learn/courses/30/lessons/12948?language=python3)
- 문자열 복습!

[Programmers] 22-12-25 (핸드폰 번호 가리기/Lv1)

---

chaeeun/BOJ/그래프/유기농배추.py

[[1012] 유기농 배추](https://www.acmicpc.net/problem/1012)
- `BFS` 새로운 유형

[BOJ] 22-12-26 (유기농 배추/Silver2)

---

chaeeun/Programmers/Lv1/하샤드수.py

[[12947] 하샤드 수](https://school.programmers.co.kr/learn/courses/30/lessons/12947)
- 형변환!! `문자` <-> `숫자`

[Programmers] 22-12-27 (하샤드 수/Lv1)

---

chaeeun/Programmers/Lv1/정수내림차순으로배치하기.py

[[12933] 정수 내림차순으로 배치하기](https://school.programmers.co.kr/learn/courses/30/lessons/12933?language=python3)
- 자료형 복습: `문자` `숫자`

[Programmers] 22-12-28 (정수 내림차순으로 배치하기/Lv1)

---

minjung/백준/DFS-BFS/11404.py

[
](https://www.acmicpc.net/problem/11404)
l플로이드 기본문제 ! !

[BOJ] 22-12-28 (플로이드/Gold4)

---

minjung/백준/DFS-BFS/1238.py

[1238](https://www.acmicpc.net/problem/1238)
다익스트라 알고리즘 !
1. 시간초과 -> 힙을 이용하지 않아서 하나 하나 확인해야해서 시간초과 발생함
2. 힙을 이용한 다익스트라 구현을 확실히 알아야 할듯

[BOJ] 22-12-29 (파티/Gold3)

---

chaeeun/Programmers/Lv1/제일작은수제거하기.py

[[12935] 제일 작은 수 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/12935)
`array.index()`

[Programmers] 22-12-29 (제일 작은 수 제거하기/Lv1)

---

chaeeun/Programmers/Lv1/콜라츠추측.py

[[12943] 콜라츠 추측](https://school.programmers.co.kr/learn/courses/30/lessons/12943?language=python3)
-

[Programmers] 22-12-30 (콜라츠 추측/Lv1)

---

minjung/백준/다이나믹 프로그래밍/2839.py

[[2849] 설탕배달 (BOJ/Silver4)](https://www.acmicpc.net/problem/2839)
조건문 잘 세워서 풀면되는 문제

[BOJ] 22-12-30 (설탕배달/Silver4)

---

minjung/백준/DFS-BFS/14503.py

[[14503] 로봇 청소기 (BOJ/Gold5)](https://www.acmicpc.net/problem/14503)
bfs 문제!
방향을 초기화해줘야함

[BOJ] 22-12-31 (로봇 청소기/Gold5)

---

chaeeun/Programmers/Lv1/서울에서김서방찾기.py

[[12919] 서울에서 김서방 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/12919)
리턴에 바로 format() 써도 괜찮았다!!..!!!
`return "김서방은 {}에 있다".format(seoul.index('Kim'))`

[Programmers] 22-12-31 (서울에서 김서방 찾기/Lv1)

---

minjung/백준/자료구조/10942.py

[[10942] 팰린드롬? (BOJ/Gold4)](https://www.acmicpc.net/problem/10942)
일반적인 팰린드롬 으로 풀었을때 시간초과
dp로 풀어야함!
팰린드롬인 경우만 1로 바꿔줘서 입력값받으면 출력만 해주는 형태로 짜야 시간초과가 안된다

[10942] 팰린드롬? (BOJ/Gold4)

---

chaeyeong/[문제집]단기간성장/boj12865.cpp

boj 12865
https://www.acmicpc.net/problem/12865
다이나믹프로그래밍, 베낭문제
베낭을 안쪼개는 문제라 그냥 돌리면 됨

[BOJ] 23-01-01 (평범한 베낭/Gold5)

---

chaeeun/Programmers/Lv2/숫자의표현.py

[[12924] 숫자의 표현](https://school.programmers.co.kr/learn/courses/30/lessons/12924?language=python3#)
- 이전에 못 풀었던 문제 성공!!! ><

[Programmers] 23-01-01 (숫자의 표현/Lv2)

---

minjung/백준/DFS-BFS/9205.py

[[9205] 맥주 마시면서 걸어가기 (BOJ/Gold5)](https://www.acmicpc.net/problem/9205)
문제 그대로 푸는 그래프 문제!
그냥 조ㅑㅏ표값같이 생각하면 안되고 문제를 그대로 코드로 풀어낼줄 알아야할듯

[BOJ] 23-01-02 (맥주 마시면서 걸어가기/Gold5)

---

chaeeun/Programmers/Lv1/가운데글자가져오기.py

[[12903] 가운데 글자 가져오기](https://school.programmers.co.kr/learn/courses/30/lessons/12903)
-

[12903] 가운데 글자 가져오기

---

chaeyeong/[문제집]단기간성장/boj1655.cpp

boj1655
https://www.acmicpc.net/problem/1655
우선순위큐

[boj] 23-01-02 (가운데를 말해요/골2)

---

hyesu/그래프탐색/1012.py
hyesu/그리디/1339.py
hyesu/연습문제/최댓값과 최솟값.py

https://www.acmicpc.net/problem/1012
https://www.acmicpc.net/problem/1339
단어수학 -> 자릿수를 더해서, 자릿수가 가장 큰 순서대로 9 부터 할당한다.
유기농배추 -> BFS를 이용하려면 queue를 이용한다. 그래프 탐색을 통해 이어져 있는 것의 개수를 구한다.

[BOJ] 23-01-01 (단어수학/골드4), 23-01-02 (유기농배추/실버2)

---

hyesu/그래프탐색/4963.py

https://www.acmicpc.net/problem/4963
대각선 까지 포함
BFS

[4963] 23-01-03 (섬의 개수/실버2)

---

chaeeun/BOJ/그래프/단지번호붙이기.py

[[2667] 단지번호붙이기](https://www.acmicpc.net/problem/2667)
- BFS는 큐를 꼭 이용하자!
(구글링 없이 성공><)

[2667] 단지번호붙이기

---

chaeeun/BOJ/그래프/섬의개수.py

[[4963] 섬의 개수](https://www.acmicpc.net/problem/4963)
- 대각선으로 이동하는것도 추가!

[BOJ] 23-01-04 (섬의 개수/Silver1)

---

chaeeun/BOJ/정렬/소트인사이드.py

[[1427] 소트인사이드](https://www.acmicpc.net/problem/1427)
- 문자 <-> 숫자

[BOJ] 23-01-05 (소트인사이드/Silver5)

---

minjung/백준/다이나믹 프로그래밍/11066.py
minjung/백준/정렬/10814.py
minjung/백준/정렬/11931.py
minjung/백준/정렬/2757.py

[BOJ] 23-01-15

---

chaeyeong/3273.cpp

boj 3273
https://www.acmicpc.net/problem/3273
배열 접근 out of bounds...

[boj] 22-1-05 (두 수의 합/실3)

---

minjung/백준/다이나믹 프로그래밍/11066.py
minjung/백준/다이나믹 프로그래밍/tempCodeRunnerFile.py

[[11066] 파일 합치기 (BOJ/Gold3)](https://www.acmicpc.net/problem/11066)
이제까지 풀었던 DP 문제 중에 젤 어려웠 ..
- 계속 오류 난 이유 : 부분합을 배열로 넣ㄷ어줬는데 계산되는 부분에서 인덱스가 0일 때 -1로 들어가서 인덱스 값이 -1로 되어서 아이에 맨 뒤에값을 불러버려서 계속 마이너스 값으로 업뎃이 됐다 . .
-  백준은 pypy3로만 통과댐

[BOJ] 23-01-06 (파일 합치기/Gold3)

---

chaeeun/BOJ/정렬/수정렬하기2.py

[[2751] 수 정렬하기 2](https://www.acmicpc.net/problem/1427)
- 버블정렬 -> O(N)
- 병합정렬 -> O(NlogN) -> 이거 코드 완벽 이해

[BOJ] 수 정렬하기 2

---

chaeeun/BOJ/정렬/수정렬하기4.py

[[11931] 수 정렬하기 4](https://www.acmicpc.net/problem/11931)
- 병합정렬 내림차순

[BOJ] 23-01-07 (수 정렬하기 4/Silver5)

---

chaeeun/Programmers/Lv1/나누어떨어지는숫자배열.py

[Programmers] 23-01-08 (나누어 떨어지는 숫자배열/Lv1)

---

minjung/백준/정렬/10610.py
minjung/백준/정렬/1427.py
minjung/백준/정렬/2750.py

[2750] 수 정렬하기 (BOJ/Bronze)
[1427] 소트인사이드 (BOJ/Silver5)
[10610] 30 (BOJ/Silver4)

[BOJ] 23-01-09 

---

chaeeun/Programmers/Lv1/없는숫자더하기.py

[[86051] 없는 숫자 더하기](https://school.programmers.co.kr/learn/courses/30/lessons/86051)
- 배열에서 원하는 원소 삭제하기 : `.remove()`
`lst = [1,2,3]`
`lst.remove(2)` # 결과 : lst = [1,3]

[Programmers] 23-01-09 (없는 숫자 더하기/Lv1)

---

chaeeun/BOJ/그래프/알파벳.py

[[1987] 알파벳](https://www.acmicpc.net/problem/1987)
- DFS
- DFS -> 그래프에 있는 문자를 숫자로 바꿔서 접근..

[BOJ] 23-01-11 (알파벳/Gold4)

---

chaeeun/BOJ/스택/막대기.py

[[17608] 막대기](https://www.acmicpc.net/problem/17608)
- 스택 복습

[17608] 막대기

---

chaeeun/Programmers/Lv1/문자열내림차순으로배치하기.py

[12917] 문자열 내림차순으로 배치하기
- `chr()` <-> `ord()`
위 둘은 서로 반대 함수!

[Programmers] 23-01-13 (문자열 내림차순으로 배치하기/Lv1)

---

chaeeun/Programmers/Lv1/음양더하기.py

[Programmers] 23-01-14 (음양 더하기/Lv1)

---

chaeeun/Programmers/Lv1/내적.py

[BOJ] 23-01-15 (내적/Lv1)

---

chaeeun/BOJ/덱/회전하는큐.py

[1021] 회전하는 큐
- 최소로 움직이도록 할 수 있게 하는 조건!!

[BOJ] 23-01-16 (회전하는 큐/Silver4)

---

chaeeun/BOJ/덱/queuestack.py

[24511] queuestack
- deque의 활용
- 문제 자체가 새로워서 참고 후 이해 [liink](https://velog.io/@somyeong0623/%EB%B0%B1%EC%A4%80c-24511%EB%B2%88-queuestack)

[BOJ] 23-01-17 (queuestack/Silver3)

---

chaeeun/BOJ/브루트포스/일곱난쟁이.py

[2309] 일곱 난쟁이
- 완전탐색이지만 좀 더 효율적인 방법으로 하는방법!
9명 중 7명 선택하는 문제에서 7명의 조건을 만족하는것 말고
거꾸로 생각해서 2명의 조건을 만족하는 것을 찾고 빼기

[BOJ] 23-01-18 (일곱 난쟁이/Bronze1)

---

chaeeun/BOJ/백트래킹/N과M(1).py

[BOJ] 23-01-19 (N과 M (1)/Silver3)

---

chaeeun/BOJ/재귀/아카라카.py

[23304] 아카라카
- 팰린드롬!
- `strr` <-> `strr[::-1]`
- 출력
`strr`: abc
`strr[::-1]`: cba

[BOJ] 23-01-21 (아카라카/Silver2)

---

chaeeun/BOJ/백트래킹/N-Queen.py

[9663] N-Queen
- 백트래킹
- 대각선 같은거 찾는법: `abs()` 이용

[BOJ] 23-1-22 (N-Queen/Gold4)

---

chaeeun/BOJ/브루트포스/분해합.py

[BOJ] 23-01-22 (분해합/Bronze2)

---

chaeeun/BOJ/수학/소수구하기.py

[1929] 소수 구하기
- 소수 판별법
```
def check_prime(num):
if num == 1:
return False
else:
for i in range(2, int(num**0.5)+1):
if num % i == 0:
return False
return True
```

[BOJ] 23-01-23 (소수 구하기/Silver3)

---

chaeeun/BOJ/수학/최대공약수와최소공배수.py

[2609] 최대공약수와 최소공배수
- 최대공약수, 최소공배수

[BOJ] 23-01-23 (최대공약수와 최소공배수/Bronze1)

---

chaeeun/BOJ/수학/소인수분해.py

[11653] 소인수분해
- for문 조건 잘 체크!!

[BOJ] 23-01-24 (소인수분해/Bronze1)

---

chaeeun/BOJ/수학/소수찾기.py

[BOJ] 23-01-25 (소수 찾기/Silver5)

---

chaeeun/BOJ/수학/최소공배수.py

[13241] 최소공배수
- 최대공약수, 최소공배수 구하기 복습

[BOJ] 23-01-26 (최소공배수/Silver5)

---

chaeeun/BOJ/수학/최대공약수.py

[BOJ] 23-01-26 (최대공약수/Silver1)

---

chaeeun/BOJ/DP/피보나치수2.py

[2748] 피보나치 수 2
- 피보나치 수를 DP로 구하기!!

[BOJ] 23-01-27 (피보나치 수 2/Bronze1)

---

chaeeun/BOJ/DP/BABBA.py

[9625] BABBA
- 피보나치 dp로 푸는거 복습!
- dp 구현
1) bottom-up: 반복문 (-> 이걸로 풂. 그러니 시간초과 안남!)
2) top-down: 재귀

[BOJ] 23-01-29 (BABBA/Silver5)

---

chaeeun/BOJ/시뮬레이션/로봇청소기.py

[BOJ] 23-01-29 (로봇 청소기/Gold5)

---

chaeeun/BOJ/그리디/거스름돈.py

[BOJ] 23-01-30 (거스름돈/Bronze2)

---

chaeeun/BOJ/그리디/회의실배정.py

[1931] 회의실 배정
- 그리디 알고리즘. 구현 아이디어
- 소팅 + 람다함수 복습

[BOJ] 23-01-31 (회의실 배정/Silver1)

---

chaeeun/BOJ/그리디/동전0.py

[BOJ] 23-02-01 (동전 0/Silver4)

---

chaeeun/BOJ/그리디/한조서열정리하고옴ㅋㅋ.py

[14659] 한조서열정리하고옴ㅋㅋ
- 조건 끝까지 잘보기!!
- lambda 함수 복습

[BOJ] 23-02-02 (한조서열정리하고옴ㅋㅋ/Bronze1)

---

chaeeun/BOJ/완전탐색/숫자카드.py

[10815] 숫자 카드
- dict로 찾으면 빠르당..!

[BOJ] 23-02-03 (숫자 카드/Silver5)

---

chaeeun/BOJ/정렬/좌표압축.py

[18870] 좌표 압축
- dict 까지는 했는데 lst를 deepcopy 해서 min(lst)를 del 해줬다. -> 시간초과..
- set으로 하는 방법 찾아서 해결!

[BOJ] 23-02-04 (좌표 압축/Silver2)

---

hyesu/영어끝말잇기.py

https://school.programmers.co.kr/learn/courses/30/lessons/12981
for idx, 배열요소 in enumerate(배열)

[프로그래머스] 23-02-05 (프로그래머스/Lv2)

---

chaeeun/BOJ/그래프/그림.py

[[1926] 그림](https://www.acmicpc.net/problem/1926)
- visited 배열 만들어서 체킹 해주자.............
안하고 원래 그래프로 바로 바꿔줬더니 런타임 에러 떴다..

[BOJ] 23-02-06 (그림/Silver1)

---

chaeeun/BOJ/트리/상근이의여행.py

[[9372] 상근이의 여행](https://www.acmicpc.net/problem/9372)
- 모든 국가가 연결되어있기 때문에
`비행기 종류 최소 개수` = `국가의 수` - 1

[BOJ] 23-02-07 (상근이의 여행/Silver4)

---

chaeeun/Programmers/Lv1/행렬의덧셈.py

[Programmers] 23-02-08 (행렬의 덧셈/Lv1)

---

hyesu/튜플.py

https://school.programmers.co.kr/learn/courses/30/lessons/64065
풀이방법: 주어진 숫자들을 int 배열로 바꾸고, 원소의 개수가 작은 순서대로 정렬한 뒤 값을 중복되지 않도록 넣는다.
`findall()`을 사용하면 정규식을 이용하여 리스트형식으로 리턴할 수도 있다.

[프로그래머스] 23-02-09 (튜플/Lv2)

---

hyesu/DP/정수삼각형.py

https://school.programmers.co.kr/learn/courses/30/lessons/43105
- 리스트.copy()를 하면 부작용 없이 리스트가 잘 복사된다.
- 이차원 배열 DP를 이용 하여 해당 dp배열에 현재까지 왔을때의 최댓값을 저장했다. 마지막에는 마지막줄에 모든 최댓값 합들이 저장되어 있을 테니, 이 중에서 다시 최댓값을 찾아준다.

[43105] 정수삼각형 (프로그래머스/Lv3)

---

chaeeun/BOJ/트리/트리의부모찾기.py

[[11725] 트리의 부모 찾기](https://www.acmicpc.net/problem/11725)
- 트리 자료구조 코드로
- `dfs` 복습

[11725] 트리의 부모 찾기

---

chaeeun/Programmers/Lv1/최대공약수와최소공배수.py

[12940] 최대공약수와 최소공배수
- 최대공약수, 최소공배수 복습

[Programmers] 23-02-10 (최대공약수와 최소공배수/Lv1)

---

hyesu/[1차] 캐시.py

https://school.programmers.co.kr/learn/courses/30/lessons/17680
캐시 deque을 만들어서 해당 deque에 있는지 없는지를 검사한다.
cache = collections.deque(maxlen=cacheSize)
다른 풀이를 보다보니 maxlen이라는 것을 적용할 수도 있었다.

[프로그래머스] 23-02-12 ([1차]캐시/Lv2)

---

hyesu/그래프탐색/게임 맵 최단거리.py

https://school.programmers.co.kr/learn/courses/30/lessons/1844
- 최단거리는 BFS를 이용한다. BFS는 queue를 이용해 구현하며, 방문처리는 visited 배열을 이용한다.
- BFS 구현: 시작 노드를 큐에 넣고 방문처리 한다. -> 시작 노드를 큐에서 pop하고 pop한 노드와 연결되어있지만 방문하지 않은 노드를 다시 큐에 넣는다. 이를 큐가 빌때까지 반복한다.
- 해당 문제는 결국 1 부분만 지나갈 수 있는 최단거리문제이다. 
- 최단거리를 저장하는 2차원 배열 d와 방문여부를 저장하는 visited 배열을 만들어준다.
- 1이지만 방문하지 않은 노드들을 하나씩 방문하며 이전 거리 + 1을 해준다.
- 만약, 상대 팀 진영에 도달하지 못하면 -1을 리턴해야 하므로, 이를 판별할 수 있는 flag값을 만들어준다.
- 배열선언과 x, y를 헷갈려서 계속 런타임 에러가 났다. 주의하자!

[프로그래머스] 23-02-13 (게임 맵 최단거리/Lv2)

---

hyesu/완전탐색/숫자의 표현.py

https://school.programmers.co.kr/learn/courses/30/lessons/12924
- 하나씩 돌아가면서 판단해줌
- for문 거꾸로 돌리기
``` python
for k in range(n//2 + 1, 0, -1):
```

[프로그래머스] 23-02-13 (숫자의 표현/Lv2)

---

hyesu/정렬/H-Index.py

https://school.programmers.co.kr/learn/courses/30/lessons/42747
- list에 filter걸기
``` python
list(filter(lambda x: x>=i, citations))
```
해당 코드는 citiations 배열에서 i보다 큰 원소만 리스트로 만들어준다.
나는 가장 큰 원소부터 ~ 0까지 -1씩 내려오면서 모두 확인해주는 방식으로 구현했는데, 시간복잡도가 너무 크다.
```python 
def solution(citations):
citations.sort(reverse=True)
for idx , citation in enumerate(citations):
if idx >= citation:
return idx
return len(citations)
```
찾아보니 요렇게 해주면 시간이 훨씬 줄어든다.

[42747] H-Index (프로그래머스/Lv2)

---

.gitignore
hyesu/Programmers-Swift/Programmers-Swift/약수의 합.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12928
```swift
func solution(_ n:Int) -> Int {
if n == 0 {
return 0
}
let array = Array(1...n)
let newArray = array.filter { (n % $0 == 0) }
return newArray.reduce(0, +)
}
```
1. reduce를 이용한다
reduce의 첫 파라미터 -> 시작값
reduce의 두 번째 파라미터 -> 할 연산 (+, -, / ..)
+을 쓰면 값을 하나씩 더하게 된다.
2. sum 함수를 구현한다.
```swift
func sum(numbers: [Int]) -> Int {
return numbers.reduce(0, +)
}
print(sum(numbers: [1, 2, 3])) // 6
```
4. generic 을 이용한다. (여러 타입 가능)
```swift
extension Array where Element: Numeric {
func mySum() -> Element {
return self.reduce(0, +)
}
}
print([1, 2, 3].mySum()) // 6
print([1.1, 2.2, 3.3].mySum()) // 6.6
```

[프로그래머스] 23-02-13 (약수의 합/Lv1/Swift)

---

hyesu/스택/큐/기능개발.py

https://school.programmers.co.kr/learn/courses/30/lessons/42586
```python
from collections import deque
def solution(progresses, speeds):
answer = []
queue = deque(progresses)
speeds = deque(speeds)
while queue:
tmp = 0
for i in range(len(queue)):
queue[i] += speeds[i]
while len(queue) > 0 and queue[0] >= 100:
queue.popleft()
speeds.popleft()
tmp += 1
if tmp != 0:
answer.append(tmp)
return answer
```
큐에서 하나씩 빼주면서 판단한다. 내부 while문에서 인덱스 오류가 났는데, queue.popleft()를 해준후에 다시 queue[0]을 접근해서 그랬다. 앞으로 주의하자

[프로그래머스] 23-02-13 (기능개발/Lv2)

---

chaeeun/BOJ/큐/절댓값힙.py

[BOJ] 23-02-13 (절댓값 힙/Silver1)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/최댓값과 최솟값.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12939
(문자열).components(seperatedBy: “(자를 문자)“)
```swift
print(s) // "1 2 3 4"
print(s.components(seperatedBy: " ") // ["1", "2", "3", "4"]
```
(문자열).split(seperator: “자를문자”)
```swift
s.split(separator: " ")
```
(배열).map { Int($0)! }
```swift
print(s.components(seperatedBy: " ").map { Int($0)! }
```
[[Apple Developer Documentation](https://developer.apple.com/documentation/swift/int/init(_:)-2hmii)](https://developer.apple.com/documentation/swift/int/init(_:)-2hmii)
String을 Int로 바꾸는 경우, Optional이 리턴된다. 따라서 Optional(1) 이런식으로 안되려면 언래핑을 해줘야한다.
(배열).min()!
얘도 Optional이 리턴되므로, 언래핑해줘야 한다.
(배열).max()!

[프로그래머스] 23-02-14 (최댓값과 최솟값/Lv2/Swift)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/올바른 괄호.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12909
처음에 배열에 append하고 remove하는 형식으로 했더니 효율성에서 시간초과가 났다.
이 문제는 결국 괄호의 개수만 알면 되니까 개수만 카운트 해주면 효율성도 통과할 수 있다.

[12909] 올바른 괄호 (프로그래머스/Lv2/Swift)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/K번째수.swift

https://school.programmers.co.kr/learn/courses/30/lessons/42748?language=swift
``` swift
let slicedArray = array[i-1..<j]
```
- `sorted()` : 원본은 건들지 않고 오름차순으로 정렬된 새로운 배열을 만들어 리턴한다.
- `sort()`: 배열원본을 정렬한다. (var 배열에서만 사용할 수 있다.) 
- `sort(by: >)`: 내림차순

[42748] K번째수 (프로그래머스/Lv1/Swift)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/가장 큰 수.swift

https://school.programmers.co.kr/learn/courses/30/lessons/42746
만약 9, 34가 있으면 934랑 349중에 큰걸 찾으면 된다.
String의 덧셈은 두 문자열을 이어주는 것이기 때문에, 이를 이용해서 sort한다.
처음에 [0, 0, 0]인 경우를 생각하지 못해 하나의 테케에서 오류가 났다. (000으로 출력됨)
그래서 모든 수가 0인경우 0으로 리턴해주는 예외를 추가한다.
string 배열을 문자열로 합친다.
```swift
newNumbers // [1, 3, 4, 3]
newNumbers.map { String($0) }.joined() "1343"
```
```swift
let newNumbers = numbers.sorted {
String($0) + String($1) > String($1) + String($0)
}
```

[프로그래머스] 23-02-14 (가장 큰 수/Lv2/Swift/정렬)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/최소직사각형.swift

https://school.programmers.co.kr/learn/courses/30/lessons/86491
명함은 회전할 수 있으므로 가장 짧은 길이끼리 모으고, 가장 큰 길이끼리 모아서
각각에서 가장 큰 걸로 하면 된다.

[프로그래머스] 23-02-10 (최소 직사각형/Lv1/Swift/완전탐색)

---

chaeeun/Programmers/Lv1/직사각형별찍기.py

[Programmers] 23-02-14 (직사각형 별찍기/Lv1)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/카펫.swift

https://school.programmers.co.kr/learn/courses/30/lessons/42842
방정식을 풀어야 한다..
카펫의 전체 가로 a, 전체 세로를 b라고 하면, 해당 문제에선 다음과 같은 식을 얻을 수 있다.
- 2a+2b-4 = brown
- (a-2)(b-2) = yellow
- a>=b, a>=3, b>=3
위 두 식을 연립하면 ab = brown + yellow ==> ab = total가 나온다.
for문을 이용해 a를 하나씩 돌며 b = total/a 를 2a+2b -4 = brown에 넣고, 조건에 맞는 값을 리턴한다.
문제에서 둘다 3이상이라고 했기 때문에 3부터 반복문을 돌리고, 결국 약수중에서 중간값을 기준으로 한쪽에 몰려있는 경우는 있을 수 없으니 반까지만 돌려도 된다.

[프로그래머스] 23-02-14 (카펫/Lv2/Swift/완전탐색)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/네트워크.swift

https://school.programmers.co.kr/learn/courses/30/lessons/43162?language=swift
결국 네트워크의 묶음(덩어리)이 몇개인지 묻고 있다.
stack을 이용하여 DFS로 구현했다.
1. 방문 여부를 확인하는 visited 배열과 stack을 만든다.
2. 노드를 모두 돌며 방문하지 않은 노드를 찾은 후 그 노드를 스택에 넣고 방문처리를 한다.
3. 스택이 비어있지 않으면 노드를 꺼내서 해당 노드와 연결된 노드들을 다시 스택에 넣고 방문처리를 한다. 이 과정을 스택이 비어있을때까지 한다.
4. 스택이 모두 비었는데 아직 visited하지 않은 것이 있다면 해당 컴퓨터는 이어지지 않은 노드이므로 똑같은 과정을 반복하고, 이때 답을 +1 하면 된다.
5. 
처음에는 visited 반복문을 아래와 같이 돌렸다.
```swift
for (idx, visit) in visited.enumerated() {
/// ..
}
```
여기서 visit는 진짜 그 메모리에 있는 값이 아니라, 새로 만들어진 값이다.
그래서 visit = true로 바꿔줘도 값이 딱히 안바뀐다..  
그래서 idx만 조회해서  진짜 배열의 값에 접근하는 것으로 바꿨다.
```swift
for idx in visited.indices {
}
```
indicies를 이용하면 안전하게 배열의 인덱스를 가져올 수 있다.
물론 0..<len(배열)로도 가능하긴함
```swift
for idx in visited.indices {
}
```

[프로그래머스] 23-02-15 (네트워크/Lv3/Swift/DFS)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/S4/1764.swift

https://www.acmicpc.net/problem/1764
합집합을 이용해서 두 집합의 공통요소를 찾아낸다.
```swift
// String으로 입력받아짐
var input = readLine()!
// Int 1개 입력받기
var input = Int(readLine()!)!
// Int 2개 입력받기 (ex. n m)
var input = readLine()!.split(seperator: " ").map { Int($0)! }
let n = input[0]
let m = input[1] 
// 공백없는 숫자를 배열로 입력받기 ex ) "12345"
// Int
var nums = Array(readLine()!).map {Int(String($0))!}
// String
var nums = Array(readLine()!).map {String($0)}
```
```swift
// Array -> 집합 만들기
Set(array)
// 교집합 (intersection)
set1.intersection(set2)
// 합집합 (Union)
set1.union(set2)
// 차집합 (Subtract)
set1.subtracting(set2)
```

[1764] 듣보잡 (BOJ/실버4/Swift/문자열)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/JadenCase 문자열 만들기.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12951
처음에는 s를 공백 기준으로 나눠서 배열로 만든 후, 배열 안의 string의 가장 첫 글자를 대문자로 바꿔서 joined()을 이용해 연결해줬는데, 이러면 공백이 두 개 이상인 곳에서 문제가 생긴다.
그래서 받은 문자열 전체를 돌면서 맨 첫 글자와 공백 뒤의 글자는 upper로, 나머지 글자는 lower로 바꿔줬다.
[[Apple Developer Documentation](https://developer.apple.com/documentation/swift/string/uppercased())](https://developer.apple.com/documentation/swift/string/uppercased())
- uppercased(): 원본은 건들이지 않고 문자열 전체를 대문자로 만든다.
- lowercased(): 원본은 건들이지 않고 문자열 전체를 소문자로 만든다.
→ O(n)
String.index를 이용해야됨
subscript를 사용하면 재열로도 가능하다.

[프로그래머스] 23-02-16 (JadenCase 문자열 만들기/Lv2/Swift)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/최솟값 만들기.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12941
https://spark-chive-e55.notion.site/0ac34b7b3b944ad0ad5a66b99b343540
가장 큰 수와 가장 작은 수를 곱한 것을 더해주면 된다.
따라서 배열 A는 오름차순 배열로, B는 내림차순으로 정렬한 후 앞에서부터 곱한 것을 더해준다.

[프로그래머스] 23-02-16 (최솟값 만들기/Lv2/Swift)

---

chaeeun/Programmers/Lv1/이상한문자만들기.py

[12930] 이상한 문자 만들기
- 하나 이상의 공백을 지우기 위해서는
`str.split()`이 아닌 `str.split(' ')`으로 해줘야 한다!!!

[Programmers] 23-02-16 (이상한 문자 만들기/Lv1)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/이진 변환 반복하기.swift

https://school.programmers.co.kr/learn/courses/30/lessons/70129
https://spark-chive-e55.notion.site/2cb2114440fb42ae8dd9f821e40c1dc8
0의 개수는 filter를 이용해 개수를 카운트하고 바로 더해준다.
그리고 0을 모두 삭제한 것에서 길이를 구해 2진수를 구한다.
- 문자열에서도 적용된다.
- removeAll을 사용해 특정 조건에 있는 모든 내용들을 삭제할 수 있다. 이때 원본이 바뀐다.
```swift
a.removeAll { $0 == "0" }
```
```swift
// 2진수, 새로운 String을 리턴한다.
String(a.count, radix: 2)
```

[프로그래머스] 23-02-17 (이진 변환 반복하기/Lv2/Swift)

---

chaeeun/BOJ/DP/상자넣기.py

[[1965] 상자넣기](https://www.acmicpc.net/problem/1965)
- DP

[BOJ] 23-02-17 (상자넣기/Silver2)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/피보나치 수.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12945
https://spark-chive-e55.notion.site/4ef4a7c23ad74f77a0d41e076a5b5db5
리스트를 만들고 반복문을 이용해 피보나치수 % 1234567을 구한다.
처음엔 % 1234567을 마지막에만 해줘서 오류가 났다. (Int 범위 때문인듯)
배열 반복 만들기
```swift
// 원소가 n-1개이고, 0인 Int배열
[Int](repeating: 0, count: n-1)
```

[프로그래머스] 23-02-18 (피보나치 수/Lv2/Swift)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/다음 큰 숫자.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12911
https://spark-chive-e55.notion.site/a70dc528aec6408f9842cd7c015fa851
주어진 숫자 n부터 하나씩 돌면서 이진수로 변환 후 1을 카운트해서 비교해준다.
2진수 만들기
```swift
String(숫자, radix: 2)
```

[프로그래머스] 23-02-18 (다음 큰 숫자/Lv2/Swift)

---

chaeeun/BOJ/스택/알파벳블록.py

[ICPC_D] 알파벳 블록
- deque, stack 복습

[BOJ] 23-02-18 (알파벳 블록)

---

chaeeun/BOJ/DP/합분해.py

[[2225] 합분해](https://www.acmicpc.net/problem/1965)
- 자연수의 분할!! + 표 만들어서 차근차근 dp로 풀기

[BOJ] 23-02-19 (합분해/Gold5)

---

chaeeun/BOJ/수학/이항계수2.py

[[11051] 이항 계수 2](https://www.acmicpc.net/problem/11051)
- nCk 공식을 그대로 구현(factorial) 했었는데 조금 변형해서 구현했더니 성공했다! (-> 미리 약분되는건 약분 된 상태로 계산 되게 해줌)
- 원래는 DP로 풀려고 했는데 다르게 성공해버렸다. 담엔 DP로 풀어보잣

[11051] 이항 계수 2

---

chaeeun/Programmers/Lv1/약수의개수와덧셈.py

[[77884] 약수의 개수와 덧셈](https://school.programmers.co.kr/learn/courses/30/lessons/77884)
- 약수 구하기 복습

[Programmers] 23-02-21 (약수의 개수와 덧셈/Lv1)

---

chaeeun/Programmers/Lv1/문자열다루기기본.py

[Programmers] (문자열 다루기 기본/Lv1)

---

chaeeun/BOJ/구현/최댓값.py

[BOJ] 23-02-23 (최댓값)

---

hyesu/SwiftAlgorithm/SwiftAlgorithm/Lv2/짝지어 제거하기.swift

https://school.programmers.co.kr/learn/courses/30/lessons/12973
https://spark-chive-e55.notion.site/a9ed4b1804c34e9f93d5199ae5e45356
처음에는 냅다 돌면서 확인하려 했는데, 스택을 이용하면 되는 문제였다. 
stack을 만들고, 문자를 하나하나 돌면서 스택의 최상단 문자와 비교하여 같으면 pop, 다르면 append 해준후, 마지막에 스택의 길이가 0이면 가능, 0보다 크면 불가능이게 해주면 된다.

[프로그래머스] 23-02-24 (짝지어 제거하기/Lv2/Swift)

---

chaeeun/Programmers/Lv1/3진법뒤집기.py

[[68935] 3진법 뒤집기](https://school.programmers.co.kr/learn/courses/30/lessons/68935)
- 진법 변환

[Programmers] 23-02-24 (3진법 뒤집기/Lv1)

---

chaeeun/Programmers/Lv2/N개의최소공배수.py

[[12953] N개의 최소공배수](https://school.programmers.co.kr/learn/courses/30/lessons/12953)
- n개의 최대공약수, 최소공배수 구하기..
- 내가 짠 코든데 2개가 틀렸다...
일단 아이디어는 모든 수들을 소인수분해 해서 제곱수들의 최대만 뽑아서 계산해주기..
~~~python
def facto(dictt, num):
div = 2
cnt = 1
while div <= num:
if num % div == 0:
dictt[div] = cnt
num //= div
cnt += 1
else:
div += 1
cnt = 1
def solution(arr):
answer = 1
result = []
for i in range(len(arr)):
dictt = dict()
facto(dictt, arr[i])
for key, value in dictt.items():
result.append([key, value])
result.sort()
answer = 1
for i in range(len(result)-1):
if result[i][0] != result[i+1][0]:
answer *= result[i][0] ** result[i][1]
if len(result) >= 2 and result[-1][0] != result[-2][0]:
answer *= result[-1][0] ** result[-1][-1]
return answer
~~~

[Programmers] 23-03-01 (N개의 최소공배수/Lv2)

---

chaeeun/BOJ/구현/트럭주차.py

[[2979] 트럭 주차](https://www.acmicpc.net/problem/2979)
- 아이디어
입력으로 주어지는 시간의 최대 숫자가 100이니까 result배열 만들어놓고 값 써놓으면 됐다..! (이걸 아예 생각을 못함ㅠ)  
그래서 1이면 A, 2면 B, 3이면 C 이므로 마지막에 그렇게 계산해쥬면 됨!

[BOJ] 23-03-03 (트럭 주차/Bronze2)

---

chaeeun/BOJ/문자열/팰린드롬인지확인하기.py

[[10988] 팰린드롬인지 확인하기](https://www.acmicpc.net/problem/10988)
- 판별하기 위한 임시 숫자들도 명확하게 사용하자!!

[BOJ] 23-03-05 (팰린드롬인지 확인하기/Bronze2)

---

chaeeun/BOJ/문자열/농구경기.py

[[1159] 농구경기](https://www.acmicpc.net/problem/1159)
- 문제에서 요구하는거 꼼꼼하게 보쟈..!

[BOJ] 23-03-06 (농구경기/Bronze2)

---

chaeeun/BOJ/문자열/한국이그리울땐서버에접속하지.py

[[9996] 한국이 그리울땐 서버에 접속하지](https://www.acmicpc.net/problem/9996)
- `40m`
- 복잡한 인덱싱..
-1부터 앞으로 가는 인덱싱은 못하는 것 같다...
- 문제 조건 잘 보기..
앞뒤로 알파벳이 하나가 아니라 여러개씩 있을 수도 있다..  
ex. a*b, ac*b, abc*dex 등

[BOJ] 23-03-08 (한국이 그리울땐 서버에 접속하지/Silver3)

---

chaeeun/BOJ/DP/합분해.py
chaeeun/BOJ/문자열/비밀번호발음하기.py

\
[[4659] 비밀번호 발음하기](https://www.acmicpc.net/problem/4659)
- `for _ in ['a','e','i','o','u']:`

[BOJ] 23-03-16 (비밀번호 발음하기/Silver5)
